### ISSUE TITLE
[Project] Proposal I - Solid, Go / Gin, Rust / Rocket, Postgres, Tauri

### ISSUE THREAD

**Issue by Arcaster42** [Tersus-Light/tersus-doc-app#5]
## Background
This proposal is designed to provide a balance between performance and ease of development by introducing newer, proven technology that have high performance relative to their learning curve while using safe and security-minded languages and architecture for authentication.

## Issue
NA

## Tech Stack
| Technology | Application | Summary |
|-------------|------------|-----------|
| Solid | Frontend | A blend of Svelte and React, incredibly simple components with easily integrated features and superior performance. Has its own compiler and is fully reactive unlike React. |
| Go / Gin | Resource Server | Highly performant backend language with a small learning curve and simple concurrency. |
| Rust / Rocket | Auth Server | Arguably the most performant web backend possible with incredibly safety. |
| Postgres | SQL Database | Sufficient SQL database readily available for sandboxing and deployment. |
| Tauri | Native Desktop | Tauri uses Rust in the backend for superior performance and development safety. |

## Architecture
![image](https://user-images.githubusercontent.com/47514505/184126664-8f4ac669-16b6-471d-9aa4-c498c2a90762.png)

### Solid (Frontend)
[Solid](https://www.youtube.com/watch?v=hw3Bx5vxKl0&ab_channel=Fireship) is an evolution of React inspired by some elements of React and many elements of Svelte. It has its own compiler that allows for incredibly small bundles and near-vanilla levels of performance.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/47514505/183271228-26829f77-45e3-44b4-bd9f-a81d399038db.png">

Solid does not use a virtual DOM and allows more natural writing of HTML templating in JSX to avoid heavy use of ternary operators and, even worse, nested ternary operators with helpers like `Show` with fallbacks.

```
  return (
    <Show
      when={loggedIn()}
      fallback={<button onClick={toggle}>Log in</button>}
    >
      <button onClick={toggle}>Log out</button>
    </Show>
  )
```

Reactivity is handled with `Signals` using a similar syntax as React.

```
const [loggedIn, setLoggedIn] = createSignal(false)
```

However, where React is not truly reactive and uses schedulers, Solid uses proxies to have true reactivity. Additionally, all components truly render once allowing for some additional implementations (like `setInterval`) and avoiding issues caused by components re-rendering (like React's `useEffect` on `Strict` mode). Additionally, `useEffect` is also present here but does not require a dependency array and is handled automatically.

It is the [most loved web frameworks ](https://2021.stateofjs.com/en-US/libraries/front-end-frameworks/)at 90% satisfaction (tied with Svelte).

Ultimately, it is a great bridge between React and Svelte.

### Go / Gin (Resource Web Server)
[Gin](https://gin-gonic.com/docs/) is a light web server framework for Go.

Go itself is a compiled, very performant language with a simple syntax. It is statically typed with explicit type inference, easy concurrency patterns (which the Gin framework uses to improve performance). It does include concepts like [pointers](https://go.dev/tour/moretypes/1) that a key aspects of computer science but are usually unfamiliar to JS developers. However, understanding these concepts goes a long way to improving engineering.

Gin is a very straight-forward framework for creating clean and easily maintainable web servers. [Examples of the syntax and implementation](https://github.com/gin-gonic/examples) are available from the developers.

Go web server[ performance ranks consistently several orders of magnitude above Node](https://youtu.be/h7UEwBaGoVo?t=321) and below Rust. Development speed is typically on par with Node and above Rust.

### Rust / Rocket (Auth Web Server)
[Rust](https://www.rust-lang.org/) is currently the most performant backend language and is the [most loved language](https://survey.stackoverflow.co/2022/) for 6 years in a row. While more difficult than JavaScript and Go, it offers incredible safety as a compiled language and a superior compiler for handling errors. While it doesn't have traditional garbage collection, it has a signature concept of "ownership" for managing memory.

[Rocket](https://rocket.rs/) is a relatively simple web framework implementation of Rust. As the authentication is relatively simple, it offers an opportunity to learn and implement Rust with additional synergy with Tauri as it uses Rust in the backend.

### Postgres (Database)
Postgres is an easily accessible SQL database (with numerous free hosting options and CI/CD integration such as on Heroku). A relational database is ideal given the application will not have explicitly complex schema or significant object complexity (i.e. little or no nesting). Given the potential scale of the application with thousands of users and magnitudes more documentation, a normalized database would be ideal for maintaining and querying the data.

### Tauri
Tauri is a relatively new native desktop framework for web frameworks. Its primary attraction is the Rust backend that is incredibly performant and safe. Compared to Electron, it is compatible with more frameworks and packages, has far less memory consumption, and has a larger emphasis on security. Bundle sizes are also much smaller than other frameworks. [It benches above other native desktop frameworks in nearly every category](https://tauri.app/about/benchmarks). Built-in testing and substantial documentation make development reliable. Rust in the backend may prove to be more complex, especially for frontend developers. However, required backend implementation is comparatively simple.

### Dedicated Authentication Server
Dedicated authentication servers provide a layer of abstraction from the resource server. Using tokens, users can authenticate and then send the token to the resource server for a secondary check from the authentication server. Token refreshes will ensure highjacked tokens do not become a long-term threat. Given the public availability of the product, additional layers of security are preferable, and using performant backends, user experience will not be negatively impacted.

### Databases
Databases will be split based on their connecting server. The authentication server will maintain tokens and authentication-related credentials, while the resource server will contain primary data. This will prevent complete compromise in the event one database is penetrated or taken offline.

**Comment by dawndarkness** [comment]
This is very cool. Here are some points:

- I liked that you put example code for solid
- Although solid is the "most loved" the number of developers actually using it, or even knowing about it is small, so those most loved numbers probably only represent a proportionally small number of people.
- Interesting idea to use both Rust and Go, and your reasons for using them for each server makes sense to me. How much time would it take to learn them both and use them for each server in comparison to using one of them on both?
- Architecture section was a very good idea. I think that for me personally, I don't have a good idea about architecture and what is involved overall, so this was helpful for me.

Cheers!

**Comment by petegriffith** [comment]
Great! Very informative well written. Easy to parse for those of us with limited knowledge about these topics. I was happy to read about BE language frameworks, which I didn't find time to dig into. Being honest I used this as a template so it's hard to find anything I would quibble with that isn't addressed in my proposal. I share Julie's questions about Rust and Go - would it take more time than it's worth to use both? I am really enjoying Go for now but I feel like I've only scratched the surface. 

Thanks for this!

**Comment by wiru** [comment]
Hi @Arcaster42 

- A great read for me too. I learnt a lot from this. Especially that SolidJS exists (that's two days of my life i'll never get back)
- You mentioned Gin somehow uses Golangs great concurrency to improve performance. Is this special to Gin? Or does it have some specific trait that makes this so. I would've liked a link to something there. 
- I share the same concern with the others about two different backend frameworks. But I have no backend experience at all, so it may be that auth server don't require much set up. But the concern is there given the strict timelines. 
- A good point about Rust synergizing with Tauri. But it makes me wonder again why not do the whole backend in Rust. 
- Anyway, I learnt a lot, and I think it was very clearly written and explained, so thanks.

Cheers!
