### ISSUE TITLE
[Project] Proposal I - Svelte/graphQL/Golang/PostgreSQL/Tauri

### ISSUE THREAD

**Issue by petegriffith** [Tersus-Light/tersus-doc-app#8]
# Overview

The general theses of my proposal is that we should settle on the same technologies for the docs project that we will be using for the main project unless:

1. The docs project's business needs are significantly different enough to outweigh the advantage gained from building on technical knowledge for the main project, OR
2. There is some consideration still of what tech we're going to be using for the main project, and therefore want to try out one or more technologies for the docs project. 

At first glance, it doesn't look like the docs project will need anything that would be superfluous for the final project. 

I also am not sure that anything is _particularly_ up in the air for the final project, aside from the API pattern. Very little is set in stone, but since there seems to be a general idea for the final project, I don't see any reason to branch out.  

There are a couple of things I think would be interesting to look into for the final project but might be too big a bite for the doc project, [which I've listed at the bottom of the document](#additional-technologies).

# Issue
[Pete's Proposals 1](https://github.com/Tersus-Light/tersus-docs-app/issues/2)

# Tech Stack

| Technology | Application | Summary |
|--|--|--|
| Svelte | Front-End | A lightweight, fully-reactive javascript framework with native global state management. Boasts fantastic performance and incredibly simple and semantic syntax. Great DX. |
| SvelteKit | Fullstack framework | A Svelte framework for building web apps. Routing, SEO (superfluous?), SSR, and Vite under the hood. |
| GraphQL / Apollo (or Hasura?!) | API | An API query language/platform |
| Go | Data Server & Auth Server | A performant backend language with great tooling |
| Postgres | DB | An SQL Database that the team is already very familiar with |
| Tauri | Desktop framework | A desktop framework written in Rust, therefore fast and secure. Compatable with Svelte/SvelteKit |

# Architecture

![image](https://user-images.githubusercontent.com/72716356/184524314-49bbfe1a-618b-4f64-86a4-5c788492a2e9.png)

# Selection Criteria (tech)
## Svelte + SvelteKit
Svelte is a new but established JavaScript framework that compiles at build time, updating the actual DOM "surgically" rather than using a virtual DOM and rerendering on change (or even worse, on useEffect). Developers love working with Svelte according to [2021](https://insights.stackoverflow.com/survey/2021#section-most-loved-dreaded-and-wanted-web-frameworks) and [2022](https://survey.stackoverflow.co/2022/#section-most-loved-dreaded-and-wanted-web-frameworks-and-technologies) StackOverflow surveys. It features components with significantly less boilerplate than React/Vue making the development experience simple and clean. Crucially for us, this makes the Svelte learning curve quite manageable.
Svelte's reactivity and state management implementations are similarly simple and clean. All variables declared with `let` are reactive, and instead of `useState` or `ref()`, updating a reactive variable's state can be done by simply...updating the variable.
```js
let count = 0
count += 1
```

State management can be handled globally out of the box with Svelte's "stores". Simpler to work with than React's Context, "stores" are similar to Vuex/Pinia, but don't require outside libraries.
It's true that Svelte is a young framework and it therefore might be theoretically difficult to find and add experienced Svelte developers in the near future. However it's popularity is growing and people want to learn Svelte, and it's so simple to learn that recruiting experienced app developers who will gladly pick it up shouldn't be an issue. 

SvelteKit is Svelte's app-framework, similar to Next.js or Nuxt. Because our docs app will likely to be link heavy, SvelteKit's prefetching will make navigating noticably fast. Filename-based routing which will opinionate and simplify our dev experience, and it's built with Vite which is a revalation for DX compared to webpack.
Unfortunately, SvelteKit is still in development so using it is a risk, but it has a lot of support and momentum, and is very close to a 1.0 release.
## GraphQL
GraphQL allows a client to access a single endpoint to query any data it might need, without the need to specify new API routes for any specific slice of data needed. A graphql platform like Apollo or Hasura helps set up a "supergraph", which is essentialy a schema for all query-able data. Clients use the GraphQL query language to query the supergraph, accessing exactly the data it needs and avoiding overfetching or mutiple REST calls. Authorization can be done within the platform.
Apollo is the most common gql platform, and the one with which CC grads are most familiar. 
A graphql platform I love is Hasura and I've mentioned it at the bottom of the document.
## Golang
Go is a compiled, statically typed backend language designed by Google. It features built-in testing and very clear and easy-to-read documentation, making it simple for both new and experienced developers to learn. While it's speed (compared to a Node.js backend) will be a bit superfluous for the docs project, the final project will require a very performant back-end accessed by many users. It's a good idea to get a head start on learning Go for the development team, so using it for the docs project is a no-brainer. 

I do propose separating the auth and resource servers; however I feel that we should stick with one backend language for both servers in order to keep the learning curve manageable. I'm relatively confident that outside of TJ, none of us have much experience at all working outside of JavaScript (or SQL) and so learning Go will be a worthwhile and time-consuming challenge. 
## PostgreSQL
Neither the docs project nor the main project are such that a no-SQL DB would seem to be preferable. As we're all familiar with PostgreSQL and there's no business reason to change, I suggest sticking with PostgreSQL for our database.
## Tauri
A popular new alternative to Electron, Tauri's main selling point is that it's not basically recreating Chrome on the desktop because it doesn't use Chromium. It's therefore much lighter than Electron and isn't the resource hog that Chrome is. It's compatable with Svelte and, while written in Rust, should be simple enough to learn for our straightforward needs.

# Selection Criteria (architecture)
## Split Servers & DBs
Keeping our Auth and Resource servers separate provides some security, especially as our app's core function is authenticating and authorizing users. Users will log in to and recieve an auth token from the auth server and then use it to access resources based on provleges granted by the token and based on the user's auth level. Keeping DBs separate is an additional security layer, making sure that a breach on one DB is contained.

# Additional Technologies
| Technology | Application | Summary |
|--|--|--|
| Storybook OR Histoire | Component Library Tool | Histoire is Svelte specific|
| Hasura | GraphQL Engine | | https://www.apollographql.com/blog/graphql/golang/using-graphql-with-golang/|
| [GraphQL-Codegen](https://www.graphql-code-generator.com/) | FE gql codegen ||
| ~~Prisma~~ **Golang version scrapped** | ~~ORM~~ | ~~Typescript Compatable! (sorry, knex...)~~ |
| Future Svelte i18n integration | i18n | Possibly integrated out-of-the-box into SvelteKit 1.0 (+?), but should think about other options |

**Comment by Arcaster42** [comment]
I'll cover some points in the proposal mostly dealing with the writing.

- The overall writing style is informal. A lot of personal pronouns and casual opinions are present. When writing documentation here, use a more formal style as though it's going directly to your manager and team.
- Remove ambiguity where possible. Any sentence that contains "I'm relatively sure", "probably", or any other likelihood description should be rewritten where possible. For example, talking about others with Go experience, it would be better to actually confirm this information to write a more definitive statement. Likelihood descriptors should be use where concrete information is truly lacking.
- Along with that point, there are some placeholder lines here ("or Hasura!?", crossed out content in additional technologies). As a proposal, it should be as definitive as possible, so there shouldn't be any placeholder or deprecated content.
- Svelte and SvelteKit are listed. Which one? What are the differences with Tauri?
- Sources needed. Claims like "Svelte is popular and people want to learn it" should be sourced reliably.
- GraphQL supergraph visual representation would be really helpful.
- About Postgres, you claim there's no reason to use NoSQL, but what are these criteria?
- "Resource hog" should be replaced with something more concrete such as benchmarks or references to sources.
- Great tables, great graphs.
- Overall good breakdown of the technologies.
- Great job hitting on making a choice between REST and GraphQL.
- Very nice mentioning component library management via Storybook and Histoire.

**Comment by dawndarkness** [comment]
This was an interesting read for me. Here are some points:

- I'm loving how you structured this. It was a very easy read.
- Loved that you included a summary at the beginning
- I also thought about choosing a tech stack that could help us build upon skills that could be used in the main project, but for me, learning a new skill in itself is going to be very positive, and help build my learning/study skills
- I don't think it was really necessary to mention CC grads, as not everyone is a CC grad (in life :) ).
- I made this mistake too, but I think being a bit more detailed with the reasoning for postgres would have been good.
- Good point about keeping the databases separately.
- I like that you mentioned other languages in a general comparative sense.

Cheers, mate!

**Comment by wiru** [comment]
Hi @petegriffith 

- I agree with Julie above, I thought your proposal flowed really well. 
- I think perhaps its was a little too focused on the our current real world situation, which took away from the exercise of writing a proposal as if for a company. 
- I was little confused about Sveltekit Fullstack. Maybe you just need to explain it to me next time we chat. I dont understand what it does if we have svelte frontend and tauri native app. Is it for a mobile app? 
- Loved the explanation of GraphQL. I didnt go into enough detail in mine about why I chose GraphQL, but you explained it wonderfully i thought. 
- I felt you made a fair point on sticking to one backend language given the time frame of this project 
- Really enjoyable read, and I like your tech stack.
