### ISSUE TITLE
[Project] Project Proposal I - Svelte/Go/Postgres/Tauri

### ISSUE THREAD

**Issue by dawndarkness** [Tersus-Light/tersus-doc-app#9]
# Introduction

This proposal centers on using modern, fast and efficient technologies along with tried and true tech choices for a blend of stability and innovativeness. It focuses on providing the best user experiences through speed and efficiency, but also keeping in mind the need for security.

# Issue
#3 

# 🏛 Proposed Architecture

![techstack](https://user-images.githubusercontent.com/62203696/184336818-54d42310-b1d3-4a7e-b718-064fce708ac3.png)

<div align="center" >

 🖥  Frontend | 📡 Server | 💾 Database | 💻 Native Desktop Framework
:------- | :------- | :------- | :-------
 [Svelte](https://svelte.dev/) <img width=100/>  | [Go](https://go.dev/)<img width=120/>  |  [PostgreSQL](https://www.postgresql.org/)<img width=70/>  | [Tauri](https://tauri.app/)

</div>

### [Svelte](https://svelte.dev/)
Svelte is highly performant, and as its name would suggest, svelte. Rather than creating and manipulating a virtual DOM, it uses a compiler that moves reactivity out of the component API and into the language. To put it simply, the hard work is done when building the app with minimal javascript shipped to the browser.

As svelte uses Javascript, HTML and CSS, it can be learned quickly by programmers. Although Svelte is still a relatively new frontend framework it has gained [notice](https://2021.stateofjs.com/en-US/libraries/front-end-frameworks) and traction among the developer community for its speed and innovativeness, and thus would help us to attract talent in the future. 

![Screen Shot 2022-08-10 at 18 48 17](https://user-images.githubusercontent.com/62203696/184336932-a5843d46-183b-4ada-95bf-5dfb77a68b7e.png)

I am personally drawn to it for its simplicity. According to Rich Harris, the creator of Svelte, a comparable react component would take 40% more code, and it can be in the ballpark of 35 times faster than React and 50 times faster than Vue. Its use of topological ordering and labelled statements is also very attractive to me.

### [Go](https://go.dev/)

Go is a fast, statically typed language which was specifically developed for speed, scalability, and creating web servers by its creators at Google. It has an expressive but lightweight type system, which also makes it a relatively safe language. It is now a very well known language with a lot of resources, which I think makes it easier for developers to learn.

A concern that we may have in our programme is memory leaks. Go is a language that makes identifying memory leaks easier with tools like [ppof](https://pkg.go.dev/runtime/pprof). As a multi-threaded language that supports concurrency, it will allow functions to run in a non-blocking manner simultaneously. This creates a faster user experience.  

Care should be taken to avoid pitfalls in Go's garbage collection logic. We will need to be careful so as not to incur unneccessary additional overheads. Go gives us the tools to limit allocation by controlling the layout of data structures, as a way to mitigate this issue, but robust code reviews will be an important factor in the review process.

### [PostgreSQL](https://www.postgresql.org/)

Postgres is a well known, open source object-relational database system that is known for its reliability and performance. I think this would be a safe choice and is something that I think we would all be comfortable with using, as I'm sure we all have at least some experience with it.

### [Tauri](https://tauri.app/)

In keeping with the theme of choosing small and fast tech, Tauri is my choice for Native Desktop Framework. It is small and fast and has built in safety features which will help make the app secure. It is compatible with most frontend frameworks, including Svelte, and its core is built with Rust which is also well known for being a language used for its speed and safety.

**Comment by Arcaster42** [comment]
I'll leave some notes focusing on the writing of the proposal.

- The architecture graph shows layers but not interactions. Considering the simplicity of the layers, one could assume, but removing ambiguity is always best.
- "Svelte uses HTML, CSS, JavaScript" is over-explaining. It uses those like all front-end frameworks. Assume your audience knows what you're talking about on fundamental levels.
- Good overview of performance and ease of development. Sourcing the claim that React would require more code would be helpful. An example would be even better.
- Good job touching on Go's concurrency as that is a huge feature.
- "Faster user experience" sounds like users get through the app physically faster. "Faster response times, better user experience."
- "Unnecessary additional overheads" such as? What are the pitfalls of Go's garbage collection?
- You gave a light overview of Go but not necessarily why it would make a good fit for this project and for the specific role the server would play.
- Why is SQL appropriate for this project?
- Overall, good tech and overviews, but light on reasoning why these technologies are fitting specifically for this project.

**Comment by wiru** [comment]
Hi @dawndarkness !

- I think Svelte is a great choice. I would have liked a little more evidence to persuade me that it is as good as you say though. The I would want to verify your quote from the creator about 40% reductions, with maybe a link to some stats showing how much better it is in real world benchmarks?
-  Its a good point that we all have a little tiny bit of experience with Postgres. But I didnt feel like there was much more info to go on here. 
- Overall I really like the tech stack you chose.

Cheers, Comrade

**Comment by petegriffith** [comment]
Heya Julie, I loved this writeup! I's quite coherant and easy to read, and presents an engaging argument for your technoligies. Your individual arguments are all sound and well supported logically, although like Will said I might suggest a few more links to support some of your claims (Go is "very well known with lots of resources", Tauri is "Small and Fast", etc.

I'm also on the Svelte/Go train, so it was great to see that you came to a similar conclusion! 

Cheers!
